Section "Device"
    Identifier "SlideshowPi HDMI"
    Driver "modesetting"
    Option "AccelMethod" "none"
    Option "ShadowFB" "true"
    Option "PageFlip" "false"
    Option "UseGammaLUT" "false"
EndSection
